# api pagination constants
PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = 'limit'
# recipes models constants
COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 1440
AMOUNT_MIN = 1
AMOUNT_MAX = 32000
INGREDIENT_CHAR_MAX = 128
INGREDIENT_UNIT_MAX = 64
INGREDIENT_UNIT_MIN = 1
RECIPE_CHAR_MAX = 256
TAG_CHAR_MAX = 32
# short_link constants
MIN_RANGE = 8
MAX_RANGE = 10
MAX_HASH_LENGTH = 15
URL_MAX_LENGTH = 256
# users models constants
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
USERNAME_MAX_LENGTH = 150

